### ISSUE TITLE
Add topic to the project to get listed under "velero-plugin"

### ISSUE THREAD

**Issue by jonasrosland** [digitalocean/velero-plugin#3]
Hi!

Just wanted to make sure you were aware of an easy way to get more attention to your Velero plugin, all you need to do is to add the `velero-plugin` topic and you'll get listed among the others over at https://github.com/search?q=topic%3Avelero-plugin&type=Repositories.

**Comment by jamonation** [comment]
Thanks for pointing that out @jonasrosland - I've added the label to the project. Should I open a PR somewhere to get the velero docs pointing at this repo?

**Comment by jonasrosland** [comment]
> Thanks for pointing that out @jonasrosland - I've added the label to the project. Should I open a PR somewhere to get the velero docs pointing at this repo?

We're planning to build out a Plugin page on velero.io, would you be ok with us linking to the DigitalOcean plugin from there?

**Comment by jamonation** [comment]
For sure, thanks in advance for listing the plugin there!

**Comment by jonasrosland** [comment]
Perfect, thank you!
