### ISSUE TITLE
Error Cert Issue

### ISSUE THREAD

**Issue by Berndinox** [digitalocean/velero-plugin#4]
An error occurred: some backup storage locations are invalid: backup store for location "default" is invalid: rpc error: code = Unknown desc = RequestError: send request failed
caused by: Get https://BUCKET.SPACE.fra1.digitaloceanspaces.com/?delimiter=%2F&list-type=2&prefix=: x509: certificate is valid for *.fra1.digitaloceanspaces.com, fra1.digitaloceanspaces.com, not SPACE.BUCKET.fra1.digitaloceanspaces.com

**Comment by jamonation** [comment]
This looks like an issue with the DO cloud UI that lets you create spaces with multi-level subdomains. Could you try creating a single subdomain under fra.digitaloceanspaces.com? e.g. `bucket-space.fra1.digitaloceanspaces.com` and then try?

**Comment by Berndinox** [comment]
Hej @jamonation - i specified the full URL to the Bucket, you just have to set:

REGION.digitaloceanspaces.com
and --bucket "Bucketname"
